name: SEO Audit

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  lighthouse-seo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Audit SEO with Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://private-driver-no.vercel.app/
          uploadArtifacts: true
          temporaryPublicStorage: true
          
